### ISSUE TITLE
Discord Server? (Non-Issue)

### ISSUE THREAD

**Issue by Luigimeansme** [PhlexPlexico/mm3dr#14]
This is definitely not an issue, I just didn't know where else to place this. Is there already, or planned to be, a Discord server for this? I'd love to have a quick and easy place to check in on updates on the project. If you're not sure about making one yourself, I'm fairly familiar with managing Discord servers and I could help out with it

**Comment by PhlexPlexico** [comment]
Heya!

I do plan on making a discord server. However as stated in the readme, this project is nowhere near complete as I'm just writing the base patch (i.e. game fixes, getting addresses and structs ready for an app, etc) currently, and in its state is not really usable or would even make sense to have people try it out. Once this project becomes more usable in the future, I will definitely update the readme and whatnot to include an invite to a discord server I have. I know a lot of people are excited about this and whatnot but a project like this takes quite a bit of time to even get the groundwork started, and most of the updates you'll see are just on commits alone :)

Thanks!

**Comment by Luigimeansme** [comment]
Sorry, I must've missed the readme! Thanks for answering my question anyway!
