### ISSUE TITLE
Download link?

### ISSUE THREAD

**Issue by Shaughn-david** [PhlexPlexico/mm3dr#17]

**Comment by PhlexPlexico** [comment]
Please read the [README](https://github.com/PhlexPlexico/mm3dr/blob/master/README.md). The first three lines state that this is currently a work in progress, and this is just making patches for a randomizer app to generate playthroughs.

Thanks!

**Comment by PhlexPlexico** [comment]
Nowhere near close :) don't worry, whenever it gets finished you'll know, I appreciate the interest but I can't exactly devote my entire time to this, hence why it's open source. This project for me is more of "when I have spare time/motivation", so it's not exactly on top of my priorities list right now.
