### ISSUE TITLE
Getting on Epona prior to obtaining the Bow causes sword to disappear

### ISSUE THREAD

**Issue by KokiriHylian** [PhlexPlexico/mm3dr#79]
When I get on Epona before obtaining the Hero's Bow, the Kokiri Sword disappears from Link's model when entering a new area, and pressing B does nothing. The issue persists even after going back in time, or after resetting the game once the game has been saved.

Furthermore, once the Bow is obtained, the sword will reappear, but pressing B causes the Ocarina to be pulled out instead. The issue isn't resolved until after getting on Epona again once the Bow is obtained.

Issue found on v1.0.1-8cb274. Spoiler and placement logs are attached.
[1904347304 (Bombchu, Bombchu, Bottled Big Poe, Empty Bottle, Stone Mask).zip](https://github.com/PhlexPlexico/mm3dr/files/14018449/1904347304.Bombchu.Bombchu.Bottled.Big.Poe.Empty.Bottle.Stone.Mask.zip)

**Comment by PhlexPlexico** [comment]
Hey there!

The back in time issue is fixed and is pending release. How exactly did you get epona before bow? I forget if you need to complete the mini game which requires the bow. Does it blank out your B button after the mini game?

Thanks!

**Comment by KokiriHylian** [comment]
Hello!

In my case, I set Epona's Song as part of my starting inventory (along with the Ocarina and Kokiri Sword), so I was able to call Epona as soon as I got into Termina Field and played the song.

I know in the vanilla game, you can't normally get Epona until after you have the bow, so I'm guessing the game doesn't know how to handle not having the bow when you get on Epona, and, thus, breaks the B button item.

**Comment by PhlexPlexico** [comment]
Ah okay, so specifically having epona without bow does narrow this down. I'll take a look when I have some time, thanks for the report!

**Comment by KokiriHylian** [comment]
No problem!

**Comment by PhlexPlexico** [comment]
Once this is merged in and released this will be patched, you'll simply get a bow with no arrows once you mount Epona now instead of getting your sword stolen.

https://github.com/Z3DR/MM3D_Randomizer/pull/27

Thanks!

**Comment by PhlexPlexico** [comment]
This will be fixed in the next release in the coming days!
