### ISSUE TITLE
Spoiler Log doesnt show items?

### ISSUE THREAD

**Issue by Scathlon** [PhlexPlexico/mm3dr#80]
Heyho,

Is there a way to let the spoiler log where to find the items? All things are just marked with "???" 

If i am searching for Light Arrows i cant see where to find them.

Is there a option or am i just stupid or blind? 

Thanks c:

**Comment by PhlexPlexico** [comment]
Hey!

I believe the in game tracker will only show items that have been received. If you want, you can view the spoiler log on your SD card located at `/3ds/mm3dr/spoiler_logs/` and your hash + seed will be there. You can use something simple like Notepad/Notepad++/VSCode to view it and use ctrl+f.

I believe we still need to work on implementing the feature to have the in-game tracker to "always show" items.

Thanks!

**Comment by Scathlon** [comment]
Thanks for the answer!
