### ISSUE TITLE
B button is the Ocarina

### ISSUE THREAD

**Issue by ProudPichu22** [PhlexPlexico/mm3dr#82]
The B button somehow got reassigned to the ocarina button and it is impossible to pull out your sword.

**Comment by PhlexPlexico** [comment]
Can you please give some more context? Upload your spoiler log, how did this happen? What were the steps leading up to it?

Thanks!

**Comment by ProudPichu22** [comment]
Sorry for the context. I'm not sure how this happened but whenever I closed and opened the game it started happening. Heres my spoiler log.
[spoilerlog.zip](https://github.com/PhlexPlexico/mm3dr/files/14320202/spoilerlog.zip)

**Comment by ProudPichu22** [comment]
Closing issue because this is not a bug with the randomizer, but a glitch in the game. Fixed with riding epona.
